export { default as Navigation } from "./Navigation"
export { default as AboutMe } from "./AboutMe"
export { default as Portfolio } from "./Portfolio"
export { default as ContactMe } from "./ContactMe"
export { default as Footer } from "./Footer"